# Generated by Django 6.0.5 on 2026-05-27 05:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_category_biblio_description_biblio_published_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='status',
            field=models.IntegerField(choices=[(1, '在庫あり'), (2, '貸出中'), (3, '予約中'), (4, 'メンテナンス中'), (5, '紛失')], db_index=True, default=1, verbose_name='状況'),
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='有効フラグ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('remarks', models.TextField(blank=True, null=True, verbose_name='備考')),
                ('biblio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.biblio', verbose_name='お気に入り書誌')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
            options={
                'verbose_name': 'お気に入り',
                'verbose_name_plural': 'お気に入り',
                'unique_together': {('user', 'biblio')},
            },
        ),
    ]
