# Generated by Django 6.0.2 on 2026-04-21 05:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('books', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lending',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='申請日')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日')),
                ('remarks', models.TextField(blank=True, help_text='特記事項があれば記入してください。', null=True, verbose_name='備考')),
                ('due_date', models.DateField(verbose_name='返却期限')),
                ('return_date', models.DateField(blank=True, null=True, verbose_name='返却日')),
                ('status', models.IntegerField(choices=[(1, '貸出中'), (2, '返却済み'), (3, 'その他、備考にて記入')], db_index=True, default=1, verbose_name='状況')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lendings', to='books.book', verbose_name='書籍')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lendings', to=settings.AUTH_USER_MODEL, verbose_name='利用者')),
            ],
            options={
                'verbose_name': '貸出情報',
                'verbose_name_plural': '貸出情報',
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='申請日')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日')),
                ('remarks', models.TextField(blank=True, help_text='特記事項があれば記入してください。', null=True, verbose_name='備考')),
                ('status', models.IntegerField(choices=[(1, '入荷待ち'), (2, '準備完了（取置中）'), (3, '貸出済み'), (4, 'キャンセル'), (5, '期限切れ')], db_index=True, default=1, verbose_name='予約状況')),
                ('reserved_until', models.DateField(blank=True, null=True, verbose_name='取置期限')),
                ('is_active', models.BooleanField(default=True, verbose_name='有効な予約か')),
                ('biblio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='books.biblio', verbose_name='予約書誌')),
                ('book', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reserved_by', to='books.book', verbose_name='予約書籍')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to=settings.AUTH_USER_MODEL, verbose_name='利用者')),
            ],
            options={
                'verbose_name': '予約情報',
                'verbose_name_plural': '予約情報',
                'ordering': ['created_at'],
            },
        ),
    ]
