# Generated by Django 6.0.2 on 2026-04-21 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('em_num', models.CharField(max_length=150, unique=True, verbose_name='社員番号')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='メールアドレス')),
                ('is_active', models.BooleanField(default=True, verbose_name='有効なユーザーか')),
                ('is_staff', models.BooleanField(default=False, verbose_name='管理者か')),
                ('lending_limit', models.PositiveIntegerField(default=5, help_text='ユーザーが同時に借りられる最大冊数です。', verbose_name='貸出上限冊数')),
                ('lending_period_days', models.PositiveIntegerField(default=14, help_text='このユーザーが一度の貸出で借りられる日数です。', verbose_name='貸出可能日数')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'ユーザー',
                'verbose_name_plural': 'ユーザー',
            },
        ),
    ]
